name: Generate space invaders

on:
  schedule: # every 12 hours
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      # Writes commit-invaders.svg and commit-invaders-dark.svg and force-pushes them to the output branch.
      - uses: Goblinlordx/commit-invaders@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_user_name: ${{ github.repository_owner }}
          output_branch: output
